### ISSUE TITLE
GTK3/gi-repository git master support?

### ISSUE THREAD

**Issue by heyLu** [mvz/gir_ffi#1]
Hi,

i quite like the idea of doing desktop programming/prototyping in Ruby, but sadly I didn't get around to play with it until now.
I mostly work with Ruby 1.9.x (git) and a more or less recent version of GTK (3.x plus recent gi and so on), but I keep getting weird errors with it. In particular I get a `NoMethodError` even when just trying the examples. I am sure that FFI works right and ruby-gir-ffi even works with GTK2 as installed by the system, but not with the recent versions I compiled.

Here is the error in all it's glory:

```
~/t/ruby/ruby-gir-ffi/examples$ ruby 01_empty_window.rb
ruby 01_empty_window.rb (eval):3:in `init': undefined method `gint32_to_inoutptr' for GirFFI::ArgHelper:Module (NoMethodError)
from /home/mimi/t/ruby/ruby-gir-ffi/lib/gir_ffi/overrides/gtk.rb:21:in `init_with_auto_argv'
from 01_empty_window.rb:11:in `<main>'
```

FFI should really work, because the `hard_coded.rb` example works. Ruby reports itself as `ruby 1.9.3dev (2011-03-04 trunk 31020) [x86_64-linux]`.
Do you have any idea why it doesn't work for me? Can I help you with fixing/testing these things? That would really be great! :)

Thank you in advance.
